debug: true

server:
  port: 8085
  servlet:
    context-path: /users-service

spring:
  application:
    name: users-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
